- id: '1737519145208'
  alias: do_house_awake_summer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.house_awake
    to: 'on'
  condition: "{{ now().month in [6,7,8,9] }}"
  action:
  - service: script.hvac_awake_summer
    data: {}
  mode: single
- id: '1737519145209'
  alias: do_house_awake_winter
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.house_awake
    to: 'on'
  condition: "{{ now().month not in [6,7,8,9] }}"
  action:
  - service: script.hvac_awake_winter
    data: {}
  mode: single
- id: '1737519182354'
  alias: do_house_asleep
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.house_awake
    to: 'off'
  condition: []
  action:
  - service: script.hvac_asleep
    data: {}
  mode: single
