
sensor:
  - platform: min_max
    name: temp_dn_beds
    type: mean
    entity_ids:
      - sensor.invalid
      - sensor.tze200_a8sdabtg_ts0601_4_nona_temperature_2
      - sensor.tze200_a8sdabtg_ts0601_5_sharon_temperature
      - sensor.tze200_a8sdabtg_ts0601_6_yaya_temperature
  - platform: min_max
    name: temp_dn_kitchen
    type: mean
    entity_ids:
      - sensor.invalid
      - sensor.tze200_a8sdabtg_ts0601_7_kitchen_temperature
  - platform: min_max
    name: temp_up_beds
    type: mean
    entity_ids:
      - sensor.invalid
      - sensor.tze200_a8sdabtg_ts0601_1_kathy_temperature
      - sensor.tze200_a8sdabtg_ts0601_2_micka_temperature
      - sensor.tze200_a8sdabtg_ts0601_3_lisel_temperature
  - platform: min_max
    name: temp_up_loft
    type: mean
    entity_ids:
      - sensor.invalid
      - sensor.tze200_a8sdabtg_ts0601_blank_loft_temperature
  - platform: template
    sensors:
      temp_dn_beds_target:
        unit_of_measurement: "째F"
        value_template: >-
          {% if is_state('input_boolean.house_awake', 'on') %}
            {{ states.sensor.temp_dn_beds.state | float }}
          {% else %}
            {{ states.sensor.temp_dn_beds.state | float + 10 }}
          {% endif %}
      temp_dn_kitchen_target:
        unit_of_measurement: "째F"
        value_template: >-
          {% if is_state('input_boolean.house_awake', 'on') %}
            {{ states.sensor.temp_dn_kitchen.state | float }}
          {% else %}
            {{ states.sensor.temp_dn_kitchen.state | float + 10 }}
          {% endif %}
      temp_up_beds_target:
        unit_of_measurement: "째F"
        value_template: >-
          {% if is_state('input_boolean.house_awake', 'on') %}
            {{ states.sensor.temp_up_beds.state | float }}
          {% else %}
            {{ states.sensor.temp_up_beds.state | float + 10 }}
          {% endif %}
      temp_up_loft_target:
        unit_of_measurement: "째F"
        value_template: >-
          {% if is_state('input_boolean.house_awake', 'on') %}
            {{ states.sensor.temp_up_loft.state | float }}
          {% else %}
            {{ states.sensor.temp_up_loft.state | float + 10 }}
          {% endif %}

input_boolean:
  house_awake:
    name: "House Awake"
    icon: mdi:home-import-outline

script:
  hvac_awake_summer:
    sequence:
      - service: climate.set_temperature
        data:
          hvac_mode: cool
          temperature: 72
        target:
          entity_id:
            - climate.midea_upstairs_bedrooms_ir
            - climate.midea_upstairs_loft_ir
            - climate.midea_downstairs_bedrooms_ir
            - climate.midea_downstairs_kitchen_ir
      - service: climate.set_fan_mode
        data:
          fan_mode: auto
        target:
          entity_id:
            - climate.midea_upstairs_bedrooms_ir
            - climate.midea_upstairs_loft_ir
            - climate.midea_downstairs_bedrooms_ir
            - climate.midea_downstairs_kitchen_ir
  hvac_awake_winter:
    sequence:
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 68
        target:
          entity_id:
            - climate.midea_upstairs_bedrooms_ir
            - climate.midea_upstairs_loft_ir
            - climate.midea_downstairs_bedrooms_ir
            - climate.midea_downstairs_kitchen_ir
      - service: climate.set_fan_mode
        data:
          fan_mode: auto
        target:
          entity_id:
            - climate.midea_upstairs_bedrooms_ir
            - climate.midea_upstairs_loft_ir
            - climate.midea_downstairs_bedrooms_ir
            - climate.midea_downstairs_kitchen_ir
  hvac_asleep:
    sequence:
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 62
        target:
          entity_id:
            - climate.midea_upstairs_bedrooms_ir
            - climate.midea_upstairs_loft_ir
            - climate.midea_downstairs_bedrooms_ir
            - climate.midea_downstairs_kitchen_ir
      - service: climate.set_fan_mode
        data:
          fan_mode: auto
        target:
          entity_id:
            - climate.midea_upstairs_bedrooms_ir
            - climate.midea_upstairs_loft_ir
            - climate.midea_downstairs_bedrooms_ir
            - climate.midea_downstairs_kitchen_ir
