
# Onboard mature and stable ESP-12F WIFI module, large capacity 4M BYTE FLASH

# https://www.diymore.cc/products/ac-dc-power-supply-esp8266-wifi-four-way-relay-module-esp-12f-development-board
# RY1 = GPIO16
# RY2 = GPIO14
# RY3 = GPIO12
# RY4 = GPIO13

# https://www.diymore.cc/products/5v-power-supply-esp8266-wifi-dual-channel-relay-module-esp-12f-development-doard
# RY1 = GPIO5
# RY2 = GPIO4

esphome:
  name: aosmith

esp8266:
  board: esp12e
  framework:
    version: recommended

api:
ota:
  platform: esphome

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

switch:
  - platform: gpio
    pin: GPIO5
    id: relay_vacation
  - platform: gpio
    pin: GPIO4
    id: relay_normal
  - platform: template
    id: switch_vacation
    name: Water Heater Vacation
    icon: mdi:water-boiler-off
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - script.execute: script_apply
    on_turn_off:
      - script.execute: script_apply

script:
  - id: script_apply
    mode: queued
    then:
      if:
        condition:
          switch.is_on: switch_vacation
        then:
          - switch.turn_on: relay_normal
          - delay: 0.5s
          - switch.turn_off: relay_normal
          - delay: 0.5s
          - switch.turn_on: relay_vacation
          - delay: 0.5s
          - switch.turn_off: relay_vacation
        else:
          - switch.turn_on: relay_normal
          - delay: 0.5s
          - switch.turn_off: relay_normal

time:
  - platform: sntp
    on_time:
      - seconds: 0
        minutes: 0
        hours: 12
        then:
          - script.execute: script_apply
