
esphome:
  name: dump_ir

esp8266:
  board: esp12e
  framework:
    version: recommended

api:
ota:
  platform: esphome

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

remote_receiver:
  pin: GPIO14
  dump: all
