esphome:
  name: dim_office
  friendly_name: Office
  comment: Office

bk72xx:
  board: generic-bk7231n-qfn32-tuya

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

api:
ota:
  platform: esphome

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

tuya:
  # DPIDs processed from schema model: 000003w4ro

light:
- platform: tuya
  id: dimmer_switch
  name: "Dimmer Switch"
  switch_datapoint: 1
  dimmer_datapoint: 2
  min_value_datapoint: 3
  max_value: 1490

number:
  - platform: tuya
    number_datapoint: 2
    name: Brightness
    min_value: 10
    max_value: 1490
    step: 1
  - platform: tuya
    number_datapoint: 3
    name: Brightness Min
    min_value: 10
    max_value: 1000
    step: 1
  - platform: tuya
    number_datapoint: 5
    name: Brightness Max
    min_value: 700
    max_value: 1490
    step: 1

select:
  - platform: tuya
    enum_datapoint: 4
    name: Led Type
    optimistic: true
    options:
      0: Led
      1: Incandescent
      2: Halogen
  - platform: tuya
    enum_datapoint: 101
    name: Switch LED Brightness
    optimistic: true
    options:
      0: "Off"
      1: Low
      2: High
  - platform: tuya
    enum_datapoint: 102
    name:  On Control
    optimistic: true
    options:
      0: Gradual
      1: Instant
      2: Switch

