
# RED = GND
# WHI = 5V
# YEL = TX
# ORG = RX

substitutions:
  zone: e_bed
  zone_friendly: "East Bedroom"

esphome:
  name: mitsu_$zone

esp8266:
  board: esp01_1m
  framework:
    version: recommended

api:
ota:
  platform: esphome

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

climate:
  - platform: cn105
    id: mitsu_$zone
    name: "Mitsubishi $zone_friendly"
    update_interval: 2s

sensor:
  - platform: uptime
    name: Uptime
