
# RED = GND
# WHI = 5V
# YEL = TX
# ORG = RX

substitutions:
  zone: sw_bed
  zone_friendly: "Southwest Bedroom"
  remote_temp_sensor: sensor.tze200_a8sdabtg_ts0601_4_temperature

esphome:
  name: mitsu_$zone

esp8266:
  board: esp01_1m
  framework:
    version: recommended

api:
ota:
  platform: esphome

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 1
  rx_pin: 3

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

climate:
  - platform: cn105
    id: mitsu_$zone
    name: "Mitsubishi $zone_friendly"
    update_interval: 2s
    remote_temperature_timeout: 120min
    on_state:
      - lambda: |-
          auto current_f = (x.current_temperature * (9.0/5.0)) + 32.0;
          auto target_f = (x.target_temperature * (9.0/5.0)) + 32.0;
          auto delta_f = current_f - target_f;
          ESP_LOGD("mitsu", "current=%f target=%f delta=%f", current_f, target_f, delta_f);
          if (x.mode == CLIMATE_MODE_FAN_ONLY && delta_f <= -1) {
            ESP_LOGD("mitsu", "too cold; moving from fan to heat");
            id(script_heat).execute();
          } else if (x.mode == CLIMATE_MODE_HEAT && delta_f >= 1) {
            ESP_LOGD("mitsu", "too hot; moving from heat to fan");
            id(script_fan).execute();
          }

script:
  - id: script_heat
    mode: single
    then:
      - climate.control:
          id: mitsu_$zone
          mode: "OFF"
      - delay: 5s
      - climate.control:
          id: mitsu_$zone
          mode: "HEAT"
  - id: script_fan
    mode: single
    then:
      - climate.control:
          id: mitsu_$zone
          mode: "OFF"
      - delay: 5s
      - climate.control:
          id: mitsu_$zone
          mode: "FAN_ONLY"

sensor:
  - platform: uptime
    name: Uptime
  - platform: homeassistant
    name: "Remote Temperature Sensor"
    entity_id: ${remote_temp_sensor}
    internal: false
    disabled_by_default: true
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
      - lambda: return (x - 32) * (5.0/9.0);
      - clamp:
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - heartbeat: 15s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: "id(mitsu_$zone).set_remote_temperature(x);"
