esphome:
  name: projector
  friendly_name: Projector
  comment: Projector

esp8266:
  board: esp01_1m
  framework:
    version: recommended

logger:
  baud_rate: 0
  level: ERROR

api:
ota:
  platform: esphome

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://brothware/epson-projector-esphome
    components:
      - epson_projector

uart:
  id: projector_uart
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

epson_projector:
  id: projector
  uart_id: projector_uart
  model: "generic"
  update_interval: 5s

switch:
  - platform: epson_projector
    projector_id: projector
    power:
      name: "Projector Power"

binary_sensor:
  - platform: epson_projector
    projector_id: projector
    power_state:
      name: "Projector Power State"

sensor:
  - platform: epson_projector
    projector_id: projector
    lamp_hours:
      name: "Lamp Hours"

# Force inclusion of base components required by the Epson integration
number:
select:
text_sensor:
