esphome:
  name: tub
  friendly_name: Tub
  comment: Tub

esp32:
  board: m5stack-atom
  framework:
    type: arduino

logger:
  baud_rate: 0
  level: ERROR

api:
ota:
  platform: esphome

web_server:
  port: 80
  auth:
    username: !secret wifi_ssid
    password: !secret wifi_password

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://ylianst/esp-iq2020

# Make sure tx/rx pins are correct for your device.
# GPIO26/32 is ok for M5Stack-ATOM + Tail485, look in GitHub devices link for your device.
uart:
  id: SpaConnection
  tx_pin: GPIO26
  rx_pin: GPIO32
  baud_rate: 38400

iq2020:
   uart_id: SpaConnection
   polling_rate: 65
   port: 1234

# If using Celsius units on the hot tub remote, replace _f_ with _c_ in the three entries below.
# Feel free to remove any sensor that are not relevant for your hot tub.
sensor:
  - platform: iq2020
    current_f_temperature:
      name: Current Temperature
    target_f_temperature:
      name: Target Temperature
    outlet_f_temperature:
      name: Heater Outlet
    power_l1:
      name: Pumps Power
    power_heater:
      name: Power Heater
    power_l2:
      name: Heater Power
    pcb_f_temperature:
      name: Controller Temperature

switch:
  - platform: iq2020
    name: Lights
    id: lights_switch
    icon: "mdi:lightbulb"
    datapoint: 0
  - platform: iq2020
    name: Spa Lock
    id: spa_lock_switch
    icon: "mdi:lock"
    datapoint: 1
  - platform: iq2020
    name: Temperature Lock
    id: temp_lock_switch
    icon: "mdi:lock"
    datapoint: 2
  - platform: iq2020
    name: Clean Cycle
    id: clean_cycle_switch
    icon: "mdi:vacuum"
    datapoint: 3
  - platform: iq2020
    name: Summer Timer
    id: summer_timer_switch
    icon: "mdi:sun-clock"
    datapoint: 4

fan:
  - platform: iq2020
    name: Jets 1
    id: jets1
    icon: "mdi:turbine"
    datapoint: 0
    speeds: 1
  - platform: iq2020
    name: Jets 2
    id: jets2
    icon: "mdi:turbine"
    datapoint: 1
    speeds: 2

climate:
  - platform: iq2020
    id: tub_climate
    name: Temperature
    celsius: false

text_sensor:
  - platform: iq2020
    versionstr:
      name: Version
  - platform: template
    name: "Current Time"
    id: current_time
    icon: "mdi:clock"
    lambda: |-
      return id(homeassistant_time).now().strftime("%H:%M:%S");
    update_interval: 10s

script:
  - id: script_pre_peak
    mode: queued
    then:
      lambda: |-
        auto call = id(tub_climate).make_call();
        call.set_target_temperature(38);
        call.perform();
  - id: script_on_peak
    mode: queued
    then:
      lambda: |-
        auto call = id(tub_climate).make_call();
        call.set_target_temperature(28);
        call.perform();
  - id: script_off_peak
    mode: queued
    then:
      lambda: |-
        auto call = id(tub_climate).make_call();
        call.set_target_temperature(35);
        call.perform();

time:
  - platform: sntp
    id: homeassistant_time
    timezone: "America/Denver"
    on_time:
      - seconds: 0
        minutes: 0
        hours: 12
        then:
          - script.execute: script_pre_peak
      - seconds: 0
        minutes: 0
        hours: 17
        then:
          - script.execute: script_on_peak
      - seconds: 0
        minutes: 0
        hours: 21
        then:
          - script.execute: script_off_peak
