
substitutions:
  zone: dn_beds
  zone_friendly: "Downstairs Bedrooms"

esphome:
  name: midea_$zone

esp8266:
  board: esp12e
  framework:
    version: recommended

api:
ota:
  platform: esphome

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0

remote_transmitter:
  id: ir_tx
  pin: GPIO4
  carrier_duty_percent: 50%

climate:
  - platform: midea_ir
    id: midea_ir_$zone
    name: "Midea $zone_friendly (IR)"
    sensor: temp_from_ha
    use_fahrenheit: true

sensor:
  - platform: homeassistant
    id: temp_from_ha
    entity_id: sensor.temp_$zone
    internal: true
  - platform: homeassistant
    id: target_from_ha
    entity_id: sensor.temp_$zone_target
    internal: true
    filters:
      - throttle: 10s
      - heartbeat: 2min
      - debounce: 1s
    on_value:
      remote_transmitter.transmit_midea:
        code: !lambda |-
          return {0xA4, 0x82, 0x48, 0x7F, (uint8_t)(id(target_from_ha).state - 31)};
